@baseUrl = http://localhost:8080
@contentType = application/json

###
GET {{baseUrl}}/greeting
Content-Type: {{contentType}}

###
GET {{baseUrl}}/greeting?name=DarkCode
Content-Type: {{contentType}}

###
GET {{baseUrl}}/chat?prompt=Que es Spring Boot y para que sirve
Content-Type: {{contentType}}

###
GET {{baseUrl}}/chat?prompt=Explicame Api Rest como si tuviera 8 años
Content-Type: {{contentType}}

###
GET {{baseUrl}}/chat?prompt=Explicame Api Rest como si fuera un junior en Java
Content-Type: {{contentType}}

###
POST {{baseUrl}}/chat?prompt=Diferencias entre monolitos y microservicos
Content-Type: {{contentType}}

###
POST {{baseUrl}}/chat
Content-Type: text/plain

¿Cuáles son las ventajas de usar microservicios sobre un monolito?

###
POST {{baseUrl}}/chat-expert
Content-Type: text/plain

Diferencias entre Docker y Kubernetes en pocas palabras

###
POST {{baseUrl}}/chat-expert
Content-Type: text/plain

Que es la inyeccion de depencias en Spring

###
POST {{baseUrl}}/chat-expert
Content-Type: text/plain

Explica que es un bean de spring

###
POST {{baseUrl}}/chat-expert
Content-Type: text/plain

Que es JPA, para que se usa y como se usa en una app de Spring