spring.application.name=springai-openai
spring.config.import=optional:file:.env[.properties]
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini
spring.ai.openai.chat.max-tokens=800